version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    container_name: kibana01
    image: docker.elastic.co/kibana/kibana:7.0.0
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.0.0
    volumes:
      - /home/ec2-user/elastic-stack/logstash-conf/:/usr/share/logstash/pipeline/
      - /tmp/input:/tmp/input
    ports:
      - 5044:5044
    networks:
      - esnet
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    networks:
      - esnet

volumes:
  esdata01:
    driver: local

networks:
  esnet:
